// ==UserScript==
// @name         JAV 添加跳转在线观看
// @namespace    https://github.com/ANDonekey/javjump
// @version      1.0
// @author       ANDonekey
// @description  为 JavDB、JavBus、JavLibrary、JMVBT 等站点添加跳转在线观看的链接
// @license      MIT
// @icon         https://javdb.com/favicon-32x32.png
// @homepageURL  https://github.com/ANDonekey/javjump
// @supportURL   https://github.com/ANDonekey/javjump/issues
// @include      /^https?:\/\/(\w*\.)?javdb(\d)*\.com\/v.*$/
// @include      /^https?:\/\/(\w*\.)?(javbus|seejav|javsee)*\.(com|cc|me|life|bid).*$/
// @include      /^https?:\/\/(\w*\.)?javlibrary\.com.*$/
// @include      /^http.*\/cn\/\?v=jav.*$/
// @include      /^https?:\/\/(\w*\.)?jmvbt\.com\/content_(uncensored|censored)\/.*\.htm$/
// @match        *://*.app.javdb457.com/*
// @match        *://*.javdb457.com/*
// @match        *://*.javdb.com/*
// @match        *://*.v90f.com/*
// @match        *://*.jmvbt.com/content_uncensored/*.htm
// @match        *://*.jmvbt.com/content_censored/*.htm
// @require      https://update.greasyfork.org/scripts/522123/1511104/tampermonkey%20parallel.js
// @require      https://cdn.jsdelivr.net/npm/preact@10.25.4/dist/preact.min.js
// @connect      dmm.co.jp
// @connect      jable.tv
// @connect      missav.ws
// @connect      123av.com
// @connect      supjav.com
// @connect      www.bestjavporn.com
// @connect      javmenu.com
// @connect      jav.guru
// @connect      www.javmost.ws
// @connect      hayav.com
// @connect      avjoy.me
// @connect      paipancon.com
// @connect      ggjav.com
// @connect      www.av01.media
// @connect      highporn.net
// @connect      evojav.pro
// @connect      18av.mm-cg.com
// @connect      javhub.net
// @connect      javgg.net
// @connect      7mmtv.sx
// @connect      fcjav.com
// @connect      javbus.com
// @connect      javdb.com
// @connect      javlibrary.com
// @grant        GM_addStyle
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @downloadURL  https://raw.githubusercontent.com/ANDonekey/javjump/main/JAV%20%E6%B7%BB%E5%8A%A0%E8%B7%B3%E8%BD%AC%E5%9C%A8%E7%BA%BF%E8%A7%82%E7%9C%8B.user.js
// @updateURL    https://raw.githubusercontent.com/ANDonekey/javjump/main/JAV%20%E6%B7%BB%E5%8A%A0%E8%B7%B3%E8%BD%AC%E5%9C%A8%E7%BA%BF%E8%A7%82%E7%9C%8B.meta.js
// ==/UserScript==
